name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto a la rama que usas para desplegar (por ejemplo, main o master)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 4: Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HK_KEY }}  # Usa el token de acceso personal
          publish_dir: ./  # Publica desde la raíz